---
sidebar: sidebar 
permalink: install-setup/cluster-setup.html 
keywords: afx, afx system, cluster setup, setup 
summary: 'Após a instalação do hardware AFX, você pode concluir a configuração do cluster ONTAP. Esse processo envolve fases de configuração relacionadas que devem ser executadas sequencialmente. Como parte disso, você pode opcionalmente adicionar os nós de computação de dados (DCNs) que executam o AI Data Engine (AIDE), permitindo que o cluster de storage AFX e o cluster DCN operem como um único sistema gerenciado pelo mesmo plano de controle ONTAP.' 
---
= Configure seu cluster ONTAP do sistema de armazenamento AFX
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Após a instalação do hardware AFX, você pode concluir a configuração do cluster ONTAP. Esse processo envolve fases de configuração relacionadas que devem ser executadas sequencialmente. Como parte disso, você pode opcionalmente adicionar os nós de computação de dados (DCNs) que executam o AI Data Engine (AIDE), permitindo que o cluster de storage AFX e o cluster DCN operem como um único sistema gerenciado pelo mesmo plano de controle ONTAP.



== Prepare-se para configurar um sistema de storage AFX

Antes de configurar seu cluster ONTAP, você deve revisar os requisitos principais do AFX e as considerações adicionais do AIDE para garantir que tenha todas as informações e recursos necessários para concluir o processo de configuração com sucesso.



=== Requisitos principais do AFX

Existem vários requisitos essenciais a serem considerados ao configurar seu cluster AFX.

.Instalação de hardware
Certifique-se de ter concluído a instalação de hardware do seu sistema AFX. Para mais informações, consulte link:../install-setup/install-setup-workflow.html["Instale seu sistema AFX"].

.Endereçamento IP básico
Você precisa da seguinte configuração de endereçamento IP:

* Endereço IP de gerenciamento de cluster
+
O endereço IP de gerenciamento do cluster é um endereço IPv4 exclusivo para a interface de gerenciamento do cluster usado pelo administrador do cluster para acessar o SVM do administrador e gerenciar o cluster.  Você pode obter esse endereço IP com o administrador responsável por atribuir endereços IP na sua organização.

* Máscara de sub-rede de rede
+
Durante a configuração do cluster, o ONTAP requer um conjunto de interfaces de rede apropriadas para sua configuração.  Você pode ajustar a recomendação se necessário.



.Configuração de rede adicional
Você também precisará das seguintes informações de rede relacionadas:

* Endereço IP do gateway de rede
* Nomes de domínio DNS
* Endereços IP do servidor de nomes DNS
* Endereços IP do servidor NTP
* Máscara de sub-rede




=== Considerações adicionais sobre o AIDE

Ao instalar e configurar o AFX pela primeira vez, você pode incluir opcionalmente NetApp AI Data Engine (AIDE). Se você pretende configurar AIDE, primeiro precisará fazer o seguinte:

* Certifique-se de  https://docs.netapp.com/us-en/ai-data-engine/install-setup/aide-hardware-requirements.html["instalar AIDE"^]conectar e anexar os nós de computação à rede de storage AFX.
* Obtenha os endereços e qualquer configuração de rede relacionada aos nós de computação de dados.




== Executar configuração inicial do cluster

Você pode conectar seu dispositivo laptop ao cluster AFX e definir vários valores de configuração global.

.Sobre esta tarefa
Há quatro áreas do cluster AFX que devem ser configuradas inicialmente.  Os três primeiros são obrigatórios, enquanto o último é opcional.

.Passos
. Descubra sua rede de cluster.
+
.. Conecte seu laptop ao switch de gerenciamento e acesse os computadores e dispositivos da rede.
.. Abra o Explorador de Arquivos.
.. Selecione *Rede*; clique com o botão direito e selecione *Atualizar*.
.. Selecione o ícone ONTAP e aceite quaisquer certificados exibidos na tela.
+
A interface do usuário do Gerenciador do Sistema é exibida.



. Defina a senha do administrador.
+
Forneça e verifique a senha para o `admin` conta. Selecione *Continuar*.

. Configure os endereços IP para o cluster AFX e os nós do controlador.
+
Forneça endereços IP e máscaras de sub-rede.

. Se você estiver instalando AI Data Engine com seu sistema de storage AFX, forneça os endereços IP dos três nós AIDE DCN.
. Configure os serviços de rede, incluindo DNS e NIS. Selecione *Continue*.
+
Defina os detalhes dos seus servidores DNS e NTP.

. Opcionalmente, configure a criptografia.
+
Você pode definir os detalhes para criptografia de cluster. Selecione *Continuar*.

+

NOTE: Para obter informações sobre como criar um cluster para um ambiente que não seja Windows, consulte link:https://docs.netapp.com/us-en/ontap/software_setup/setup-cluster.html["Crie um cluster ONTAP e junte os nós."^].



.O que vem a seguir
Você será redirecionado para a página de login do Gerenciador de Sistema.  Execute os passos descritos em<<Configuração completa do cluster>> .



== Configuração completa do cluster

Após a configuração inicial ser realizada, você pode concluir a configuração do cluster ONTAP usando o Gerenciador do Sistema.

.Sobre esta tarefa
Há três áreas do cluster ONTAP do sistema AFX configuradas durante a instalação.  Complete todos os três, se possível, mas somente o primeiro é necessário.

.Antes de começar
Você precisa ter as seguintes informações:

* Detalhes de configuração da VLAN.
* Detalhes de configuração do NAS e/ou S3.


.Passos
. Sign in no Gerenciador do Sistema usando a conta de administrador fornecida durante a configuração inicial do cluster.  Observe a janela pop-up no canto superior direito com três opções de configuração.
. Selecione *VLAN e marcação* e selecione as opções de rede apropriadas para seu ambiente.
. Selecione *Serviços de rede* e configure os protocolos de acesso do cliente para o SVM de dados padrão.
. Selecione *Contêiner de dados* e crie um volume ou bucket S3.


.O que vem a seguir
* Se você incluiu AIDE como parte da configuração do cluster AFX, será necessário executar etapas de configuração adicionais, incluindo licenciamento e autenticação. Consulte  https://docs.netapp.com/us-en/ai-data-engine/install-setup/cluster-setup-afx.html["Configurar AI Data Engine"^] para mais informações.
* Você develink:../get-started/prepare-cluster-admin.html["Prepare-se para administrar o AFX"] antes de usar seu cluster AFX em um ambiente de produção.




== Informações relacionadas

* link:../get-started/learn-about-aide.html["Saiba mais sobre o NetApp AI Data Engine"]
* link:../administer/configure-svm.html["Configurar um AFX SVM"]
* link:../get-started/prepare-cluster-admin.html["Prepare-se para administrar o AFX"]

