---
sidebar: sidebar 
permalink: faq-ontap-afx.html 
keywords: afx, afx system, faq, frequently asked questions 
summary: Esta lista de perguntas frequentes fornece respostas às perguntas que os clientes geralmente têm sobre seu sistema de armazenamento AFX.  Inclui conceitos e terminologia que podem ser úteis ao explorar o AFX com mais detalhes ou executar tarefas administrativas avançadas. 
---
= Perguntas frequentes sobre sistemas de armazenamento AFX
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Esta lista de perguntas frequentes fornece respostas para dúvidas que você possa ter sobre seu sistema de armazenamento AFX.  Inclui conceitos e terminologia que podem ser úteis ao explorar o AFX com mais detalhes ou executar tarefas administrativas avançadas.



== Em geral

.O que é uma personalidade ONTAP ?
ONTAP é uma plataforma de armazenamento robusta e versátil, conhecida por seu conjunto abrangente de recursos e adaptabilidade a uma ampla gama de requisitos de armazenamento.  Embora essa flexibilidade o torne uma excelente escolha para organizações com cargas de trabalho diversas, alguns clientes podem se beneficiar de uma solução de armazenamento mais personalizada e otimizada para as necessidades de seu ambiente específico.

Para atender a essas necessidades especializadas, alguns sistemas de armazenamento NetApp oferecem personalidades ONTAP distintas, cada uma das quais inclui um conjunto de recursos projetados para dar suporte aos requisitos exclusivos do cliente.  Uma personalidade ONTAP é normalmente uma combinação de recursos de hardware e software, desenvolvida especificamente para oferecer uma experiência otimizada para casos de uso específicos.  A NetApp fornece três personalidades ONTAP :

ONTAP unificado:: A personalidade do Unified ONTAP oferece um amplo conjunto de recursos de gerenciamento de dados, suportando protocolos NAS, SAN e S3 para máxima flexibilidade.  Esta é a oferta principal da NetApp , disponível em sistemas AFF e FAS , bem como em implantações virtualizadas, como ONTAP Select e Cloud Volumes ONTAP.
AFX:: A personalidade do AFX ONTAP fornece uma solução desagregada projetada para atender aos rigorosos requisitos de cargas de trabalho NAS e S3 de alto desempenho, incluindo aplicativos de IA/ML.  Os sistemas AFX oferecem recursos especializados para clientes que exigem armazenamento de arquivos e objetos escalável e de alto rendimento.
ASA r2:: A personalidade do ASA r2 ONTAP fornece uma solução desagregada projetada especificamente para ambientes somente SAN. https://docs.netapp.com/us-en/asa-r2/["Sistemas ASA r2"^]   simplifique a experiência de armazenamento para cargas de trabalho em bloco, fornecendo gerenciamento simplificado e desempenho otimizado para clientes SAN.


Ao oferecer essas distintas personalidades ONTAP , a NetApp permite que as organizações selecionem uma solução de armazenamento alinhada com seus requisitos operacionais e cargas de trabalho de aplicativos.

.Posso alterar a personalidade ONTAP do meu sistema de armazenamento NetApp ?
Não. A personalidade do seu sistema de armazenamento ONTAP é imutável e não pode ser alterada.  Por exemplo, você não pode converter ou atualizar um sistema de armazenamento FAS ou AFF (que executa a personalidade Unified ONTAP ) para um sistema de armazenamento AFX.

.As interfaces do System Manager para as diferentes personalidades do ONTAP parecem muito semelhantes.  Como posso determinar a personalidade de um sistema específico?
No Gerenciador do Sistema, selecione *Cluster* no painel de navegação esquerdo e depois *Visão geral*.  Você verá a personalidade exibida na página.  Como alternativa, você pode emitir o comando "system node show" na CLI.  Você também pode determinar a personalidade de um cluster ONTAP usando a API REST; consultelink:./rest/first-call.html["Sua primeira chamada de API REST do sistema AFX"] para mais detalhes.

.O que significa "desagregado" no contexto dos sistemas de armazenamento AFX?
O termo "desagregado" pode ter dois significados diferentes, embora relacionados, com AFX, dependendo do contexto.

Um conceito importante para começar é o desacoplamento da capacidade de computação nos nós do controlador das prateleiras de armazenamento.  Com o AFX, os componentes de computação e armazenamento do cluster não estão mais fortemente acoplados como acontece com os sistemas FAS e AFF , que executam a personalidade Unified ONTAP .  Em vez disso, eles são conectados por meio de switches de cluster.  Cada controlador de nó AFX tem uma visão completa de todo o pool de armazenamento do cluster.

O segundo conceito relacionado ao armazenamento desagregado é que os agregados e o gerenciamento RAID são removidos como entidades administráveis.  Uma camada de abstração de armazenamento dentro do AFX configura e gerencia automaticamente os aspectos de baixo nível do armazenamento, incluindo os discos físicos e grupos RAID.  Isso permite que o administrador do AFX se concentre na configuração de armazenamento de alto nível com base em volumes e buckets.



== Interoperabilidade

.Posso misturar nós do sistema AFX com nós do sistema AFF, ASA ou FAS no mesmo cluster ONTAP ?
Não. Cada personalidade ONTAP é diferente.  Por exemplo, você não pode misturar nós AFX e Unified ONTAP no mesmo cluster.

.Se eu quiser usar sistemas que executam o Unified ONTAP (FAS, AFF, ASA) com sistemas AFX para SnapMirror ou FlexCache, qual versão do ONTAP eu preciso?
As regras de versão do SnapMirror para AFX são idênticas às do Unified ONTAP.  Isso significa que para replicar do Unified ONTAP, o sistema de origem deve estar dentro do intervalo de versões suportado.  Para replicar do AFX, o sistema Unified ONTAP deve estar no ONTAP 9.16.1 ou posterior (a versão mais antiga suporta o recurso Advanced Capacity Balancing).  Para FlexCache, as mesmas regras se aplicam aos sistemas de origem e destino, conforme descrito em https://www.netapp.com/pdf.html?item=/media/7336-tr4743.pdf["TR-4743"^] .

Existem algumas diferenças no suporte para volumes FlexGroup .  Um volume FlexGroup no AFX não pode ser um volume de origem para um volume FlexCache usando o modo Writeback.

.Posso fazer chamadas de API ONTAPI (ZAPI) para um cluster AFX?
Não. Somente a API REST ONTAP é suportada pelo AFX.  Qualquer código de automação que use ZAPI precisa ser convertido para a API REST para uso com o AFX.



== Conceitos avançados

.Quais são os protocolos de dados suportados por um sistema de armazenamento AFX?
Os protocolos de dados suportados pelo AFX incluem o seguinte:

* NFSv3, NFSv4.0, NFSv4.1, NFSv4.2
* SMB2.x, SMB3.x
* S3
* NDMP


.Os protocolos de dados operam de forma diferente no AFX?
Não. Os protocolos de dados no AFX operam da mesma maneira que nos sistemas AFF e FAS .

.O Particionamento Avançado de Disco (ADP) é usado no AFX?
Não. O ADP não é usado com o AFX.  Como não há agregados raiz com o AFX, o recurso ADP não é necessário para maximizar a eficiência do espaço em disco.

.Posso usar diferentes tipos de switches para a rede de backend do meu sistema de armazenamento AFX?
Não. Somente switches especificamente aprovados e fornecidos com a plataforma de armazenamento AFX são suportados pela rede de backend.

.Como o armazenamento em um cluster AFX é organizado?
Todos os discos e prateleiras de armazenamento conectados a um cluster AFX fazem parte de uma Zona de Disponibilidade de Armazenamento (SAZ).  Cada cluster AFX suporta apenas um SAZ que não pode ser compartilhado entre clusters AFX (exceto para replicação do SnapMirror e operações do FlexCache ).

Cada nó tem visibilidade de todo o armazenamento na SAZ.  Quando prateleiras de armazenamento são adicionadas a um cluster, o ONTAP adiciona automaticamente os discos.

.Como funciona uma operação de movimentação de volume no Unified ONTAP em comparação ao AFX?
Com o Unified ONTAP, é possível realocar um volume sem interrupções de um nó ou agregado para outro no cluster.  Isso é realizado usando uma operação de cópia em segundo plano com a tecnologia SnapMirror , onde um novo volume de destino é criado no novo local.  Dependendo do tamanho do volume e da utilização dos recursos do cluster, o tempo que leva para uma movimentação de volume ser concluída pode variar.

Com a AFX, não há agregados.  Todo o armazenamento está contido em uma única Zona de Disponibilidade de Armazenamento que pode ser acessada por todos os nós do cluster.  Como resultado, as movimentações de volume nunca precisam realmente copiar os dados.  Em vez disso, todas as movimentações de volume são realizadas com atualizações de ponteiros entre os nós.  Isso é chamado de Zero Copy Volume Move (ZCVM) e acontece instantaneamente porque nenhum dado é realmente copiado ou movido.  Este é essencialmente o mesmo processo de movimentação de volume usado com o Unified ONTAP sem a cópia do SnapMirror .

Observe que, na versão inicial, os volumes serão movidos apenas em cenários de failover de armazenamento e quando nós forem adicionados ou removidos do cluster.  Esses movimentos são controlados somente pelo ONTAP.

.Como o AFX determina onde colocar os dados na SAZ?
O AFX inclui um recurso conhecido como Gerenciamento Automatizado de Topologia (ATM), que responde a desequilíbrios de objetos do sistema e do usuário.  O objetivo principal do ATM é equilibrar volumes em todo o cluster AFX.  Quando um desequilíbrio é detectado, uma tarefa interna é acionada para distribuir uniformemente os dados entre os nós ativos.  Os dados são realocados usando o ZCVM, que só precisa copiar e atualizar os metadados do objeto.
