---
settings:
  name: AFX
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: pt-br,us-en,de-de,es-es,fr-fr,it-it,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentação AFX
    url: "/index.html"
  - section: release-notes
  - section: get-started
  - section: administer
  - section: svm-admin
  - section: rest
  - section: learn-more
  - title: Perguntas frequentes
    url: "/faq-ontap-afx.html"
  - title: Avisos legais
    url: "/legal-notices.html"
product-family:
  name: ONTAP
  repo: ontap-family
