---
sidebar: sidebar 
permalink: administer/view-insights.html 
keywords: afx, afx system, insights, view insights 
summary: Você pode usar o recurso Insights do ONTAP System Manager para exibir atualizações de configuração sugeridas que estejam alinhadas às práticas recomendadas da NetApp .  Essas alterações podem otimizar a segurança e o desempenho, bem como outras áreas do seu cluster AFX. 
---
= Veja insights para otimizar seu sistema de armazenamento AFX
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o recurso _Insights_ do ONTAP System Manager para exibir atualizações de configuração sugeridas que estejam alinhadas às práticas recomendadas da NetApp .  Essas alterações podem otimizar a segurança e o desempenho do seu cluster AFX.

Por exemplo, o recurso Autonomous Ransomware Protection (ARP) está disponível com o AFX e fornece proteção anti-ransomware.  O Insights informará se o ARP não estiver configurado.

.Sobre esta tarefa
Cada um dos insights é apresentado como um bloco ou cartão separado na página que você pode escolher implementar ou descartar.  Você também pode selecionar o link de documentação associado para saber mais sobre uma tecnologia específica.

.Passos
. No Gerenciador do Sistema, selecione *Análise* e depois *Insights*.
. Revise as recomendações disponíveis.


.O que vem a seguir
Execute qualquer uma das ações recomendadas para implementar as práticas recomendadas de configuração do AFX.
