---
sidebar: sidebar 
permalink: get-started/compare-unified-ontap.html 
keywords: afx, afx system, compare afx, compare unified ontap 
summary: 'Os sistemas NetApp AFX executam uma personalidade personalizada do ONTAP que difere da personalidade do ONTAP (chamada de Unified ONTAP) que é executada no armazenamento AFF e FAS .  Você deve estar ciente de como os sistemas AFX são semelhantes e diferentes dos sistemas FAS e AFF .  Isso fornece uma perspectiva valiosa e pode ser útil ao implantar o AFX em seu ambiente.' 
---
= Compare o sistema de armazenamento AFX com os sistemas AFF e FAS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Os sistemas NetApp AFX executam uma personalidade personalizada do ONTAP que difere da personalidade do ONTAP (chamada de Unified ONTAP) que é executada no armazenamento AFF e FAS .  Você deve estar ciente de como os sistemas AFX são semelhantes e diferentes dos sistemas FAS e AFF .  Isso fornece uma perspectiva valiosa e pode ser útil ao implantar o AFX em seu ambiente.


TIP: A documentação do AFX inclui links para vários tópicos no site de documentação do Unified ONTAP para obter detalhes sobre recursos que se comportam da mesma maneira, independentemente da personalidade do ONTAP .  O conteúdo adicional fornece mais profundidade, o que pode ser útil ao administrar seu sistema de armazenamento AFX.



== Diferenças de configuração

Existem algumas áreas em que a configuração do AFX difere dos sistemas AFF e FAS .

Balanceamento de Capacidade Avançado:: O recurso avançado de balanceamento de capacidade, controlado usando o `-gdd` O parâmetro CLI é habilitado por padrão para todos os volumes FlexGroup .




== Recursos do Unified ONTAP não suportados ou restritos

O NetApp AFX é otimizado para cargas de trabalho de NAS e objetos de alto desempenho.  Por conta disso, existem diferenças em relação ao AFF e ao FAS , assim como em relação aos outros sistemas de armazenamento Unified ONTAP .  Os seguintes recursos não estão disponíveis no NetApp AFX; a lista está organizada por recurso principal ou área funcional.  Você também deve revisar as atualizações e alterações do AFX emlink:../release-notes/whats-new-9171.html["O que há de novo"] com base na sua versão.



=== Bloco e SAN

* Administração SAN e acesso do cliente
* LUNs e namespaces NVMe
* Provisionamento espesso de volumes




=== Agregados e armazenamento físico

* MetroCluster
* agregados físicos pertencentes ao nó
* Gestão de RAID
* Criptografia agregada da NetApp (NAE)
* Desduplicação em nível de agregação
* SyncMirror (espelhamento agregado)
* Hierarquização do FabricPool




=== Replicação de dados (SnapMirror)


NOTE: A replicação de dados é suportada em ambas as direções entre o Unified ONTAP e o AFX, com as mesmas restrições de versionamento descritas em https://docs.netapp.com/us-en/ontap/data-protection/compatible-ontap-versions-snapmirror-concept.html["Versões ONTAP compatíveis para relacionamentos SnapMirror"^] (com algumas pequenas exceções).

* Não é possível replicar um volume de um sistema AFF ou FAS que contenha um namespace LUN ou NVMe.
* Os volumes FlexGroup só podem ser replicados do AFX para o Unified ONTAP versão 9.16.1 ou posterior (devido à necessidade do Balanceamento de Capacidade Avançado).




=== Gerenciabilidade

* API ONTAPI (ZAPI)
* APIs REST para funcionalidades não suportadas (como MetroCluster)
* Algumas limitações iniciais nas APIs REST para estatísticas de desempenho
* Suporte do AIQ Unified Manager
* Grafana Harvest versão 25.08.1 e posterior
* NetApp Trident versão 25.10 e posterior




== Alterações na interface da linha de comando

O ONTAP CLI disponível com o AFX geralmente espelha o CLI disponível com os sistemas AFF e FAS .  Mas há várias diferenças, incluindo:

* Novos comandos AFX relacionados a:
+
** Exibindo a capacidade da zona de disponibilidade de armazenamento
** Mídia de inicialização


* Nenhum comando relacionado a SAN
* Os comandos de gerenciamento agregado não são mais necessários
* A exibição agregada agora mostra toda a Zona de Disponibilidade de Armazenamento (SAZ).




== Informações relacionadas

* link:../get-started/system-design.html["Características do sistema AFX"]
* link:../get-started/software-architecture.html["Detalhes da arquitetura AFX"]
* link:../faq-ontap-afx.html["Perguntas frequentes sobre sistemas de armazenamento AFX"]
* link:../administer/additional-ontap-cluster.html["Administração adicional do cluster AFX"]
* link:../administer/additional-ontap-svm.html["Administração adicional do AFX SVM"]

