---
sidebar: sidebar 
permalink: get-started/ontap-afx-storage.html 
keywords: afx, afx system, learn, workloads, hardware, afx 1k, nx224, cisco 
summary: O sistema de armazenamento NetApp AFX é baseado em uma arquitetura de armazenamento de última geração que evolui o modelo de armazenamento ONTAP para uma solução NAS desagregada de alto desempenho.  O AFX oferece suporte a cargas de trabalho de arquivos e objetos com tecnologias avançadas e técnicas de processamento que proporcionam desempenho extremamente alto. 
---
= Saiba mais sobre os sistemas de armazenamento AFX
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O sistema de armazenamento NetApp AFX é baseado em uma arquitetura de armazenamento de última geração que evolui o modelo de armazenamento ONTAP para uma solução NAS desagregada de alto desempenho.  O AFX oferece suporte a cargas de trabalho de arquivos e objetos com tecnologias avançadas e técnicas de processamento que proporcionam desempenho extremamente alto.



== Cargas de trabalho típicas de aplicativos

O sistema de armazenamento NetApp AFX atende às demandas exclusivas típicas de ambientes de IA/ML e outros aplicativos centrados em dados relacionados. O sistema de armazenamento AFX é ideal para organizações que gerenciam diversas cargas de trabalho diferentes, incluindo:

* Treinamento e refinamento de modelo iterativo associados ao aprendizado profundo, onde são necessários alta largura de banda contínua e acesso a grandes conjuntos de dados.
* Processamento de diversos tipos de dados, incluindo texto, imagens e vídeo.
* Aplicações de inferência em tempo real com baixa latência onde são necessárias janelas de tempo de resposta rigorosas.
* Pipelines de ciência de dados e aprendizado de máquina que podem se beneficiar do gerenciamento de dados de autoatendimento por engenheiros e cientistas de dados.
* Cargas de trabalho que exigem alta simultaneidade e E/S paralela, como sistemas multi-GPU com transporte RDMA.




== Características do projeto do sistema

O sistema AFX tem diversas características de design que lhe permitem operar como uma plataforma NAS de alto desempenho.

Desvincule os recursos de armazenamento e computação:: Ao contrário dos sistemas de armazenamento AFF e FAS , os elementos de armazenamento e computação AFX do cluster são desacoplados.  Os controladores AFX não estão restritos a acessar um conjunto limitado de discos locais.
Remoção de gerenciamento de agregados e RAID:: O administrador de armazenamento não precisa mais gerenciar os agregados e grupos RAID.  A AFX lida com essas tarefas, o que simplifica a administração e oferece uma oportunidade para que não especialistas gerenciem seus dados.
Pool de armazenamento único para o cluster:: A dissociação da computação e do armazenamento do AFX, juntamente com o gerenciamento simplificado do armazenamento, resulta em um único pool de armazenamento.  Esta Zona de Disponibilidade de Armazenamento (SAZ) está disponível para todos os nós controladores em um cluster AFX. Verlink:../faq-ontap-afx.html["Perguntas frequentes sobre sistemas de armazenamento AFX"] para mais detalhes.
Alto desempenho:: O AFX foi criado para o alto desempenho necessário para aplicativos especializados de IA/ML.  Ele pode fazer uso mais eficiente de hardware moderno para fornecer largura de banda alta e sustentada com latência ultrabaixa.
Simplicidade operacional:: O pool de armazenamento único, juntamente com outros recursos, incluindo gerenciamento automático de armazenamento, fornece um modelo administrativo e operacional muito mais simples.
Escalabilidade:: O conjunto de nós controladores e prateleiras de armazenamento em um cluster pode ser expandido de forma independente com base nas necessidades da aplicação.  Há requisitos administrativos limitados e interrupções ao adicionar controladores ou prateleiras.
Melhor mobilidade de dados:: Os volumes podem ser movidos entre os nós do controlador de cluster sem interrupções, sem realmente copiar dados.  Em vez disso, os ponteiros de diretório e índice de metadados são atualizados.  Isso melhora drasticamente o desempenho durante procedimentos administrativos típicos, bem como a recuperação em cenários de falha.




== Infraestrutura de hardware

O sistema de armazenamento NetApp AFX oferece uma solução unificada de hardware e software que cria uma experiência simplificada específica para as necessidades dos clientes de NAS de alto desempenho.

Os seguintes componentes de hardware são usados com clusters AFX:

* Controladores AFX 1K
* Prateleiras NX224
* Switches Cisco Nexus 9332D-GX2B ou Nexus 9364D-GX2A




== Informações relacionadas

* https://www.netapp.com/afx/["NetApp AFX"^]

