---
sidebar: sidebar 
permalink: get-started/ontap-afx-storage.html 
keywords: afx, afx system, learn, workloads, hardware, afx 1k, nx224, cisco 
summary: O sistema de armazenamento NetApp AFX é baseado em uma arquitetura de armazenamento de última geração que evolui o modelo de armazenamento ONTAP para uma solução NAS desagregada de alto desempenho.  O AFX oferece suporte a cargas de trabalho de arquivos e objetos com tecnologias avançadas e técnicas de processamento que proporcionam desempenho extremamente alto. 
---
= Saiba mais sobre os sistemas de armazenamento AFX
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O sistema de armazenamento NetApp AFX é baseado em uma arquitetura de armazenamento de última geração que evolui o modelo de armazenamento ONTAP para uma solução NAS desagregada de alto desempenho.  O AFX oferece suporte a cargas de trabalho de arquivos e objetos com tecnologias avançadas e técnicas de processamento que proporcionam desempenho extremamente alto.



== Cargas de trabalho típicas de aplicativos

O sistema de armazenamento NetApp AFX atende às demandas exclusivas de cargas de trabalho de objetos NAS e S3 que exigem alto desempenho e escalabilidade independente.  Essas aplicações se beneficiam de um design avançado baseado em alta concorrência e E/S paralela.  O AFX é ideal para organizações que implementam e gerenciam diversos tipos de cargas de trabalho de aplicativos, incluindo:

* Treinamento e refinamento de modelo iterativo associados ao aprendizado profundo, onde são necessários alta largura de banda contínua e acesso a grandes conjuntos de dados.
* Processamento de diversos tipos de dados, incluindo texto, imagens e vídeo.
* Aplicações de inferência em tempo real com baixa latência onde são necessárias janelas de tempo de resposta rigorosas.
* Pipelines de ciência de dados e aprendizado de máquina que podem se beneficiar do gerenciamento de dados de autoatendimento por engenheiros e cientistas de dados.




== Características do projeto do sistema

O sistema AFX tem diversas características de design que lhe permitem operar como uma plataforma NAS de alto desempenho.

Desvincule os recursos de armazenamento e computação:: Diferentemente de outros sistemas de armazenamento NetApp ONTAP , os elementos de computação e armazenamento de um cluster AFX são desacoplados e unidos por meio de uma rede comutada.  A propriedade do disco não está mais vinculada a nós específicos, o que proporciona diversas vantagens.  Por exemplo, os componentes de computação e armazenamento de um cluster AFX podem ser expandidos independentemente.
gerenciamento automatizado de armazenamento:: Os agregados físicos não estão mais disponíveis para o administrador de armazenamento AFX.  Em vez disso, o AFX gerencia automaticamente as alocações de capacidade virtual para os nós, bem como a configuração do grupo RAID, quando novas gavetas de armazenamento são adicionadas ao cluster.  Este modelo simplifica a administração e oferece a oportunidade para que pessoas sem formação específica na área gerenciem seus dados.
Pool de armazenamento único para o cluster:: Como os nós e gabinetes de armazenamento são independentes no NetApp AFX, toda a capacidade de armazenamento do cluster é reunida em um único pool conhecido como Zona de Disponibilidade de Armazenamento (SAZ).  Os discos e gavetas em uma SAZ estão disponíveis para todos os nós de armazenamento em um cluster AFX para operações de leitura e gravação.  Além disso, todos os nós do cluster podem participar da reconstrução dos discos em caso de falha. Consultelink:../faq-ontap-afx.html["Perguntas frequentes sobre sistemas de armazenamento AFX"] para mais detalhes.
Alto desempenho:: O NetApp AFX oferece largura de banda elevada e sustentada com latência ultrabaixa, sendo projetado para cargas de trabalho de NAS e objetos de alto desempenho.  A AFX utiliza o hardware mais moderno e gabinetes de armazenamento capazes de lidar com uma alta proporção de nós por disco, graças à sua arquitetura exclusiva.  Aumentar a capacidade dos nós de armazenamento além da proporção típica de 1:1 (nó:prateleira) maximiza o perfil de desempenho possível dos discos até seus limites.  Este design proporciona eficiência e alta densidade de armazenamento para suas aplicações mais críticas.
Independente e em grande escala:: Graças aos nós e racks de armazenamento desacoplados, um cluster AFX pode ser expandido de forma independente e sem interrupções, de acordo com as necessidades da sua aplicação.  Você pode adicionar nós de armazenamento para obter mais CPU e taxa de transferência ou adicionar gavetas para obter mais capacidade de armazenamento e desempenho de disco.  A arquitetura NetApp AFX traz novas possibilidades para o tamanho máximo do seu cluster.  Para obter os limites mais recentes para o cluster AFX com base na sua versão do ONTAP , consulte o NetApp Hardware Universe.
Mobilidade de dados sem cópia:: Os clientes NAS e de objetos acessam volumes no cluster ONTAP .  Você pode realocar volumes entre os nós sem interrupções para atingir suas metas de balanceamento de capacidade e desempenho.  Com o Unified ONTAP, a movimentação de um volume de dados é realizada usando a tecnologia SnapMirror , o que pode levar tempo e exigir capacidade temporária adicional.  Mas com o AFX, a operação de cópia de dados não é mais necessária dentro da Zona de Disponibilidade de Armazenamento (SAZ) compartilhada.  Em vez disso, apenas os metadados do volume são movidos, o que melhora drasticamente o desempenho. Consultelink:../faq-ontap-afx.html["Perguntas frequentes sobre sistemas de armazenamento AFX"] para mais detalhes.
Funcionalidade HA aprimorada:: O NetApp AFX oferece uma série de melhorias para configuração e processamento de alta disponibilidade (HA).  O AFX elimina a necessidade de conectar diretamente os nós parceiros de alta disponibilidade (HA), permitindo que os pares de HA se comuniquem pela rede interna do cluster.  Este design oferece aos administradores a opção de implantar pares de alta disponibilidade (HA) em racks ou fileiras separadas em um data center para maior tolerância a falhas.  Além disso, a mobilidade sem cópia do AFX se estende a cenários de failover de alta disponibilidade.  Quando um nó falha, seus volumes são transferidos para o parceiro de alta disponibilidade (HA) para confirmar quaisquer gravações restantes em disco.  Em seguida, o ONTAP distribui os volumes uniformemente entre todos os nós restantes do cluster.  Isso significa que você não precisa mais considerar o desempenho de failover de armazenamento no projeto inicial de alocação de dados.




== Infraestrutura de hardware

O sistema de armazenamento NetApp AFX oferece uma solução unificada de hardware e software que cria uma experiência simplificada específica para as necessidades dos clientes de NAS de alto desempenho.


TIP: Você deve revisar olink:../faq-ontap-afx.html["Perguntas frequentes sobre sistemas de armazenamento AFX"] Para obter mais informações sobre interoperabilidade de hardware e opções de atualização.

Os seguintes componentes de hardware são usados com clusters AFX:

* Controladores AFX 1K
* Prateleiras NX224
* Switches Cisco Nexus 9332D-GX2B ou Nexus 9364D-GX2A




== Informações relacionadas

* https://hwu.netapp.com/["Hardware Universe da NetApp"^]
* https://www.netapp.com/afx/["NetApp AFX"^]

