---
sidebar: sidebar 
permalink: release-notes/whats-new-9181.html 
keywords: 'afx, release notes, what"s new, 9.18.1' 
summary: Saiba mais sobre os novos recursos incluídos no ONTAP 9.18.1 que estão disponíveis com seu sistema de armazenamento AFX. 
---
= Novidades no ONTAP 9.18.1 para sistemas de armazenamento AFX
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Saiba mais sobre os novos recursos incluídos no ONTAP 9.18.1 que estão disponíveis com seu sistema de armazenamento AFX.



== Melhorias no gerenciamento de recursos de armazenamento

[cols="2,4"]
|===
| Atualizar | Descrição 


| Posicionamento de volume aprimorado  a| 
O NetApp AFX equilibra automaticamente a distribuição de volumes entre todos os nós de um cluster.  Nas versões anteriores do ONTAP , o algoritmo de alocação era baseado no número de volumes no cluster.  A cada nó é atribuído o mesmo número de volumes, independentemente da atividade.  A partir da ONTAP 9.18.1, o algoritmo foi aprimorado para levar em consideração o desempenho dos nós ao posicionar ou mover volumes.  Isso resulta em um melhor balanceamento de desempenho entre os nós do cluster AFX e torna muito menos provável que qualquer nó individual fique sobrecarregado.

|===
.Informações relacionadas
* https://docs.netapp.com/us-en/ontap/release-notes/index.html["Destaques do lançamento do ONTAP 9"^]

